# Generated by Django 5.2.4 on 2026-01-18 17:55

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lead Note',
                'verbose_name_plural': 'Lead Notes',
                'db_table': 'lead_notes',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('whatsapp', 'WhatsApp'), ('webform', 'Web Forms'), ('calls', 'Calls')], default='manual', max_length=255)),
                ('status', models.CharField(choices=[('inprogress', 'In Progress'), ('success', 'Success'), ('failure', 'Failure')], default='inprogress', max_length=255)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('expected_closure_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employeeLeads', to=settings.AUTH_USER_MODEL)),
                ('update_notes', models.ManyToManyField(related_name='leadNotes', to='leads.leadnotes')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'db_table': 'lead_table',
            },
        ),
    ]
