# Generated by Django 5.2.4 on 2026-01-25 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='update_notes',
        ),
    ]
