# Generated by Django 5.2.4 on 2026-01-25 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_remove_lead_update_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='company',
        ),
    ]
