# Generated by Django 5.2.4 on 2026-01-26 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_remove_lead_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateLeadNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_notes_leads', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Update Lead Note',
                'verbose_name_plural': 'Update Lead Notes',
                'db_table': 'lead_notes_table',
            },
        ),
        migrations.DeleteModel(
            name='LeadNotes',
        ),
    ]
