# Generated by Django 5.2.4 on 2026-01-27 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_updateleadnotes_delete_leadnotes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updateleadnotes',
            options={'ordering': ['-created_at'], 'verbose_name': 'Update Lead Note', 'verbose_name_plural': 'Update Lead Notes'},
        ),
    ]
