# Generated by Django 5.2.4 on 2026-01-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_updateleadnotes_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempCSVImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_content', models.BinaryField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'temp_csv_imports',
            },
        ),
    ]
