# Generated by Django 5.2.4 on 2026-02-11 06:20

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_tempcsvimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter phone number (e.g. +919876543210)', max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
