# Generated by Django 5.2.4 on 2026-01-18 15:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee'), ('manager', 'Manager')], default='employee', max_length=255)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('address', models.TextField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('undisclose', 'Undisclose')], default='undisclose', max_length=255)),
                ('maritalStatus', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('undisclose', 'Undisclose')], default='Undisclose', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_phoneverified', models.BooleanField(default=False)),
                ('is_emailverified', models.BooleanField(default=False)),
                ('profileCompleted', models.BooleanField(default=False)),
                ('is_hotel_owner', models.BooleanField(default=False)),
                ('is_restuarant_owner', models.BooleanField(default=False)),
                ('is_both', models.BooleanField(default=False)),
                ('fcm_token', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(blank=True, max_length=255, null=True)),
                ('expo_token', models.CharField(blank=True, max_length=255, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
