# Generated by Django 5.2.4 on 2026-01-24 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_users_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_both',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_hotel_owner',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_restuarant_owner',
        ),
    ]
